Repository hackoregon/civic, pull requests merged in 2019-08, with the labels that each got.

#720 Accessibility landmarks
  packages/2019-template/src/components/DemoCard/demoCardMeta.js
  packages/component-library/src/Footer/Footer.js
  packages/component-library/src/Navigation/Header.js
  packages/component-library/src/PageLayout/PageLayout.js
  packages/component-library/src/ScrollToTop/ScrollToTop.js
Labels: accessibility

#722 Feature/task flow
  packages/project-disaster-trail/src/components/Game/TaskScreen/ChooseScreen.js
  packages/project-disaster-trail/src/components/Game/TaskScreen/SolveScreen.js
  packages/project-disaster-trail/src/components/Game/TaskScreen/TaskMap.js
  packages/project-disaster-trail/src/components/Game/TaskScreen/index.js
  packages/project-disaster-trail/src/constants/tasks.js
  packages/project-disaster-trail/src/state/chapters.js
  packages/project-disaster-trail/src/state/tasks.js
Labels: project:disaster-resilience

#721 Added CivicCardLayoutVisualizationOnly component
  packages/2019-template/src/components/App/index.js
  packages/component-library/package.json
  packages/component-library/src/CivicCard/CivicCardLayoutVisualizationOnly.js
  packages/component-library/src/CivicCard/CivicCardLink.js
  packages/component-library/src/index.js
  yarn.lock
Labels: type:documentation

#741 Feature/kit interface
  packages/project-disaster-trail/src/components/Game/KitScreen/Kit.js
  packages/project-disaster-trail/src/components/Game/KitScreen/KitItem.js
  packages/project-disaster-trail/src/components/Game/KitScreen/index.js
  packages/project-disaster-trail/src/components/Game/Orb.js
  packages/project-disaster-trail/src/components/Game/OrbManager.js
  packages/project-disaster-trail/src/components/Game/TaskScreen/ChooseScreen.js
  packages/project-disaster-trail/src/components/Game/TaskScreen/SolveScreen.js
  packages/project-disaster-trail/src/constants/items.js
  packages/project-disaster-trail/src/state/kit.js
Labels: project:disaster-resilience

#746 Feature/last interface
  packages/project-disaster-trail/src/components/Game/TaskScreen/ChooseScreen.js
  packages/project-disaster-trail/src/components/Game/TaskScreen/SolveScreen.js
  packages/project-disaster-trail/src/constants/tasks.js
  packages/project-disaster-trail/src/state/kit.js
Labels: project:disaster-resilience

#747 Improvements to chapter state
  packages/project-disaster-trail/src/constants/chapters.js
  packages/project-disaster-trail/src/state/chapters.js
  packages/project-disaster-trail/src/state/factories/ChapterFactory.js
Labels: project:disaster-resilience

#754 Remove redux logger from 2018 and convenience packages
  packages/2018-disaster-resilience/package.json
  packages/2018-example-farmers-markets/package.json
  packages/2018-housing-affordability/package.json
  packages/2018-local-elections/package.json
  packages/2018-neighborhood-development/package.json
  packages/2018-transportation-systems/package.json
  packages/2018/package.json
  packages/2018/src/App.js
  packages/2019-housing/package.json
  packages/2019-template/package.json
  packages/2019-transportation/package.json
  packages/civic-sandbox/package.json
  packages/dev-server/package.json
  packages/mock-wrapper/package.json
  packages/mock-wrapper/src/index.js
  packages/project-disaster-trail/package.json
  yarn.lock
Labels: quick

#761 Simplify chapter state
  packages/project-disaster-trail/src/components/Game/ChapterButtons.js
  packages/project-disaster-trail/src/components/Game/DefaultScreen/index.js
  packages/project-disaster-trail/src/components/Game/index.js
  packages/project-disaster-trail/src/constants/chapters.js
  packages/project-disaster-trail/src/state/chapters.js
Labels: project:disaster-resilience

#763 Feature/disaster theme
  packages/project-disaster-trail/src/components/Game/Orb.js
  packages/project-disaster-trail/src/components/Game/OrbManager.js
  packages/project-disaster-trail/src/components/Game/RadialGauge.js
  packages/project-disaster-trail/src/components/atoms/DurationBar/index.js
  packages/project-disaster-trail/src/constants/style.js
Labels: project:disaster-resilience

#678 Update/multi map storybook
  packages/component-library/src/MultiLayerMap/createLayers.js
  packages/component-library/stories/MultiLayerMap.story.js
  packages/component-library/stories/multiLayerMap.notes.js
Labels: type:Storybook

#776 Feature/package generator
  README.md
  _templates/package-generator/with-prompt/LICENSE.ejs.t
  _templates/package-generator/with-prompt/README.ejs.t
  _templates/package-generator/with-prompt/__variables__.ejs.t
  _templates/package-generator/with-prompt/babelrc.ejs.t
  _templates/package-generator/with-prompt/injections/2018-hot-module-injection.ejs.t
  _templates/package-generator/with-prompt/injections/2018-import-injection.ejs.t
  _templates/package-generator/with-prompt/injections/2018-package-injection.ejs.t
  _templates/package-generator/with-prompt/injections/2018-reducer-injection.ejs.t
  _templates/package-generator/with-prompt/injections/2018-route-injection.ejs.t
  _templates/package-generator/with-prompt/injections/2018-store-injection.ejs.t
  _templates/package-generator/with-prompt/mochaopts.ejs.t
  _templates/package-generator/with-prompt/package.ejs.t
  _templates/package-generator/with-prompt/prompt.js
  _templates/package-generator/with-prompt/server.ejs.t
  _templates/package-generator/with-prompt/src/client.ejs.t
  _templates/package-generator/with-prompt/src/components/App/index.ejs.t
  _templates/package-generator/with-prompt/src/index.ejs.t
  _templates/package-generator/with-prompt/src/routes.ejs.t
  _templates/package-generator/with-prompt/src/state/index.ejs.t
  _templates/package-generator/with-prompt/src/state/selectors/index.ejs.t
  _templates/package-generator/with-prompt/src/state/selectors/index.test.ejs.t
  _templates/package-generator/with-prompt/src/webpack-public-path.ejs.t
  _templates/package-generator/with-prompt/tools/testSetup.ejs.t
  _templates/package-generator/with-prompt/webpack.config.ejs.t
  package.json
  packages/2018/src/App.js
Labels: type:platform

#773 Move source link inside paragraph
  packages/2019-template/src/components/DemoCard/demoCardMeta.js
Labels: content

#694 Create Radio Button Group component. Add story to Storybook.
  packages/component-library/src/RadioButtonGroup/RadioButtonGroup.js
  packages/component-library/src/index.js
  packages/component-library/stories/RadioButtonGroup.story.js
  packages/component-library/stories/index.js
  packages/component-library/stories/radioButtonGroup.notes.md
Labels: type:Storybook, type:component-lib

#791 Add Card Layout with descriptions
  packages/component-library/src/ChartContainer/ChartContainer.js
  packages/component-library/src/ChartTitle/ChartTitle.js
  packages/component-library/src/ChartTitle/ChartTitle.test.js
  packages/component-library/src/CivicCard/CivicCardLayoutFull.js
  packages/component-library/src/CivicCard/CivicCardLayoutFullWithDescriptions.js
  packages/component-library/src/CivicCard/LayoutComponents.js
  packages/component-library/src/CivicCard/cardMetaDescriptions.js
  packages/component-library/src/index.js
  packages/component-library/stories/CivicCard.story.js
Labels: type:platform

#808 Feature/update state
  packages/project-disaster-trail/assets/laptop-color.svg
  packages/project-disaster-trail/assets/walkie-talkie-color.svg
  packages/project-disaster-trail/assets/walkie-talkie.svg
  packages/project-disaster-trail/src/components/Game/KitScreen/Kit.js
  packages/project-disaster-trail/src/constants/items.js
  packages/project-disaster-trail/src/constants/tasks.js
Labels: project:disaster-resilience

#810 Feature/centralize styles
  _templates/package-generator/with-prompt/src/components/App/index.ejs.t
  packages/2019-education/src/components/App/index.js
  packages/2019-elections/src/components/App/index.js
  packages/2019-housing/src/components/App/index.js
  packages/2019-template/src/components/App/index.js
  packages/2019-transportation/src/components/App/index.js
  packages/component-library/src/_Themes/Brand/BrandTheme.js
Labels: type:platform

#821 Change injection wildcard regex
  _templates/api-story-card/with-prompt/src/components/App/index-import.ejs.t
  _templates/local-data-story-card/with-prompt/src/components/App/index-import.ejs.t
Labels: type:platform

#832 Update all @hackoregon/component-library versions to ^4.0.0
  packages/2017/package.json
  packages/2018-disaster-resilience/package.json
  packages/2018-example-farmers-markets/package.json
  packages/2018-housing-affordability/package.json
  packages/2018-local-elections/package.json
  packages/2018-neighborhood-development/package.json
  packages/2018-transportation-systems/package.json
  packages/2018/package.json
  packages/2019-education/package.json
  packages/2019-elections/package.json
  packages/2019-housing/package.json
  packages/2019-template/package.json
  packages/2019-transportation/package.json
  packages/budget/package.json
  packages/civic-sandbox/package.json
  packages/emergency-response/package.json
  packages/homelessness/package.json
  packages/housing/package.json
  packages/project-disaster-trail/package.json
  packages/transportation/package.json
Labels: type:platform

#812 Remove old VictoryTheme files
  packages/2018-housing-affordability/src/components/ExploreHousingPolicyImplementation/SimpleCircle.js
  packages/2018-neighborhood-development/src/components/VotersOnTheMove/index.js
  packages/component-library/src/BarChart/BarChart.js
  packages/component-library/src/BaseMap/BaseMap.js
  packages/component-library/src/BaseMap/BaseMap.test.js
  packages/component-library/src/CivicCard/LayoutComponents.js
  packages/component-library/src/HorizontalBarChart/HorizontalBarChart.js
  packages/component-library/src/LineChart/LineChart.js
  packages/component-library/src/PieChart/PieChart.js
  packages/component-library/src/Scatterplot/Scatterplot.js
  packages/component-library/src/SimpleLegend/SimpleLegend.js
  packages/component-library/src/StackedAreaChart/StackedAreaChart.js
  packages/component-library/src/VictoryTheme/CivicVictoryTheme.js
  packages/component-library/src/VictoryTheme/VictoryThemeIndex.js
  packages/component-library/src/_Themes/MapGL/remoteResources.js
  packages/component-library/src/_Themes/Victory/VictoryCrazyTheme.js
  packages/component-library/src/_Themes/Victory/VictoryTheme.js
  packages/component-library/src/_Themes/VisualizationColors.js
  packages/component-library/src/_Themes/index.js
  packages/component-library/src/index.js
  packages/component-library/src/utils/chartHelpers.js
  packages/component-library/stories/BarChart.story.js
  packages/component-library/stories/HorizontalBarChart.story.js
  packages/component-library/stories/LineChart.story.js
  packages/component-library/stories/PathMap.story.js
  packages/component-library/stories/PieChart.story.js
  packages/component-library/stories/Scatterplot.story.js
  packages/component-library/stories/StackedAreaChart.story.js
  packages/project-disaster-trail/src/components/Game/TaskScreen/TaskMap.js
Labels: type:Storybook

#840 Feature/lint
  packages/2018-disaster-resilience/package.json
  packages/2018-disaster-resilience/src/components/SignificantStructuralDamage/index.js
  packages/2018-disaster-resilience/src/components/YouAndYourNeighbors/IntensityDisplay.js
  packages/2018-disaster-resilience/src/components/YouAndYourNeighbors/index.js
  packages/2018-example-farmers-markets/package.json
  packages/2018-example-farmers-markets/src/client.js
  packages/2018-example-farmers-markets/src/components/App/index.js
  packages/2018-example-farmers-markets/src/components/FarmersMarketsOverTime/index.js
  packages/2018-example-farmers-markets/src/components/PortlandFarmersMarkets/index.js
  packages/2018-housing-affordability/package.json
  packages/2018-housing-affordability/src/components/ExploreHousingPolicyImplementation/PolicyText.js
  packages/2018-housing-affordability/src/components/ExploreHousingPolicyImplementation/SelectedPolicy.js
  packages/2018-housing-affordability/src/components/ExploreHousingPolicyImplementation/SimpleCircle.js
  packages/2018-housing-affordability/src/components/ExploreHousingPolicyImplementation/index.js
  packages/2018-housing-affordability/src/components/css-utils.js
  packages/2018-local-elections/package.json
  packages/2018-local-elections/src/components/RealTimeInformationOnPoliticalCampaigns/MoneyRaisedKPI.js
  packages/2018-local-elections/src/components/RealTimeInformationOnPoliticalCampaigns/index.js
  packages/2018-neighborhood-development/package.json
  packages/2018-neighborhood-development/src/components/VotersOnTheMove/index.js
  packages/2018/src/components/HomePage.js
  packages/2018/src/components/PortlandCollectionPage.js
  packages/2019-housing/src/client.js
  packages/2019-housing/src/components/HousingDisplacement/index.js
Labels: type:platform

#828 Component library Select component
  packages/component-library/src/Select/Select.js
  packages/component-library/src/index.js
  packages/component-library/stories/Select.story.js
  packages/component-library/stories/index.js
  packages/component-library/stories/select.notes.md
Labels: type:Storybook, type:component-lib

#859 Feature/component generator
  README.md
  _templates/component-generator/with-prompt/__variables__.ejs.t
  _templates/component-generator/with-prompt/prompt.js
  _templates/component-generator/with-prompt/src/component.ejs.t
  _templates/component-generator/with-prompt/src/component.test.ejs.t
  _templates/component-generator/with-prompt/src/index-export.ejs.t
  _templates/component-generator/with-prompt/stories/component.notes.ejs.t
  _templates/component-generator/with-prompt/stories/component.story.ejs.t
  _templates/component-generator/with-prompt/stories/index-import.ejs.t
  _templates/component-generator/with-prompt/stories/index-story.ejs.t
  package.json
  packages/component-library/src/index.js
  packages/component-library/stories/index.js
Labels: type:platform

#863 Feature/authors list
  packages/2019-template/src/components/DemoCard/demoCardMeta.js
  packages/2019-template/src/components/TemplateAPICard/templateAPICardMeta.js
  packages/2019-template/src/components/TemplateFileCard/templateFileCardMeta.js
  packages/2019-transportation/src/components/TransportationCard/transportationCardMeta.js
  packages/component-library/src/CivicCard/CivicCardLayoutFull.js
  packages/component-library/src/CivicCard/CivicCardLayoutFullWithDescriptions.js
  packages/component-library/src/CivicCard/cardMetaDescriptions.js
  packages/component-library/src/CivicCard/cardMetaTypes.js
  packages/component-library/stories/CivicCard.story.js
Labels: type:Storybook, type:story-card

#860 Include all Material UI components used in Radio Button Group component
  packages/component-library/src/RadioButtonGroup/RadioButtonGroup.js
  packages/component-library/stories/RadioButtonGroup.story.js
  packages/component-library/stories/radioButtonGroup.notes.md
Labels: type:Storybook, type:component-lib

#862 Deprecated Dropdown list
  packages/component-library/stories/index.js
Labels: type:Storybook

#874 Show spiffy photo
  packages/component-library/src/CivicCard/CivicCardLayoutFull.js
  packages/component-library/src/CivicCard/CivicCardLayoutFullWithDescriptions.js
  packages/component-library/stories/CivicCard.story.js
Labels: type:Storybook

#851 Correct and Incorrect Orb handling
  packages/2018-housing-affordability/src/components/MeasuringMarketValueOfHomesInPortland/index.js
  packages/project-disaster-trail/src/components/Game/OrbManager.js
  packages/project-disaster-trail/src/components/Game/OrbManagerHelpers.js
Labels: project:disaster-resilience

#882 Fix incorrect registry injection
  _templates/api-story-card/with-prompt/src/src-registry-import.ejs.t
  _templates/api-story-card/with-prompt/src/src-registry.ejs.t
Labels: type:story-card

#883 Feature/minimal card generator
  _templates/minimal-story-card/with-prompt/__variables__.ejs.t
  _templates/minimal-story-card/with-prompt/prompt.js
  _templates/minimal-story-card/with-prompt/src/components/App/TemplateMinimalCardVisualization.ejs.t
  _templates/minimal-story-card/with-prompt/src/components/App/index-card.ejs.t
  _templates/minimal-story-card/with-prompt/src/components/App/index-import.ejs.t
  _templates/minimal-story-card/with-prompt/src/components/App/templateMinimalCardMeta.ejs.t
  _templates/minimal-story-card/with-prompt/src/components/index.ejs.t
  _templates/minimal-story-card/with-prompt/src/src-registry-import.ejs.t
  _templates/minimal-story-card/with-prompt/src/src-registry.ejs.t
  package.json
  packages/2019-template/src/components/App/index.js
  packages/2019-template/src/components/TemplateMinimalCard/TemplateMinimalCardVisualization.js
  packages/2019-template/src/components/TemplateMinimalCard/index.js
  packages/2019-template/src/components/TemplateMinimalCard/templateMinimalCardMeta.js
  packages/2019-template/src/index.js
Labels: type:story-card
