Repository hackoregon/civic, pull requests merged in 2019-06, with the labels that each got.

#519 Lint 2018-transportation-systems package
  packages/2018-transportation-systems/package.json
  packages/2018-transportation-systems/src/components/App/index.js
  packages/2018-transportation-systems/src/components/DeclineInRidership/index.js
  packages/2018-transportation-systems/src/components/DiveDeeperIntoTransportationData/index.js
  packages/2018-transportation-systems/src/components/DriversOfPublicTransitParticipation/index.js
  packages/2018-transportation-systems/src/components/ExploreBusServiceAndEquity/index.js
  packages/2018-transportation-systems/src/components/ServiceAndRidership/index.js
  packages/2018-transportation-systems/src/registry.js
  packages/2018-transportation-systems/src/state/decline-in-ridership/decline-in-ridership.test.js
  yarn.lock
Labels: good-first-review

#601 Fix script message typo
  packages/component-library/scripts/storybook.js
Labels: good-first-review

#595 Design system/scatterplot
  packages/component-library/stories/Scatterplot.story.js
  packages/component-library/stories/scatterplot.notes.md
Labels: type:Storybook, type:component-lib

#617 Feature orb component
  packages/project-disaster-trail/package.json
  packages/project-disaster-trail/src/components/Game/Orb.js
  packages/project-disaster-trail/src/components/Game/index.js
Labels: project:disaster-resilience

#589 Design System- update path map story
  packages/component-library/src/PathMap/PathMap.js
  packages/component-library/stories/PathMap.notes.md
  packages/component-library/stories/PathMap.story.js
Labels: good-first-review
